config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  root 'home#index'

  get '/about' => 'home#about'

  post '/questions' => 'home#temp'
  post '/answers' => 'home#temp'

  get '/questions/:id' => 'home#question'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord

  include HasGravatar

  belongs_to :question

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_gravatar.rb
module HasGravatar

  def gravatar
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
  end

end

app/models/question.rb
class Question < ApplicationRecord

  include HasGravatar

  has_many :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    question = Question.find(params[:answer][:question_id])
    question.answers.create(answer_params)
    session[:current_user_email] = answer_params[:email]
    redirect_to question
  end

  private
  def answer_params
    params.require(:answer).permit(:email, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).all
  end

  def about
  end

  def temp
    redirect_to root_path
  end

  def question

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
    @question = Question.find(params[:id])

    @answers = @question.answers.order(created_at: :desc).all
  end

  def create
    Question.create(question_params)
    session[:current_user_email] = question_params[:email]
    redirect_to root_path
  end

  private
  def question_params
    params.require(:question).permit(:email, :body)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user_email
    session[:current_user_email]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navigation_bar.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/about">About</a>
      </li>
    </ul>
    <div>
      <div class="navbar-text pr-2"><%= current_user_email %></div>
    </div>
    <button class="btn btn-outline-success my-2 my-sm-0" data-toggle="modal" data-target="#myModal" type="submit">Ask questions</button>
  </div>
</nav>

app/views/home/_new_answer_form.html.erb
<!-- Modal -->
<div class="modal fade" id="new_answer_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>
          <input type="hidden" name="answer[question_id]" value="<%= @question.id %>" />
          <div class="modal-body">
            <div class="form-group row">
              <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
              <div class="col-sm-10">
                <input type="email" name="answer[email]" value="<%= current_user_email %>" class="form-control" id="inputEmail" placeholder="Email" required>
              </div>
            </div>
            <div class="form-group row">
              <label for="inputAnswer" class="col-sm-2 col-form-label">Answer</label>
              <div class="col-sm-10">
                <textarea type="text" name="answer[body]" class="form-control" id="inputAnswer" placeholder="What is your Answer?" required></textarea>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_new_question_form.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for :question, url: '/questions', html: { class: 'form-horizontal' } do %>
      <div class="modal-body">
          <div class="form-group row">
            <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="question[email]" value="<%= current_user_email %>" class="form-control" id="inputEmail" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group row">
            <label for="inputQuestion" class="col-sm-2 col-form-label">Question</label>
            <div class="col-sm-10">
              <textarea type="text" name="question[body]" class="form-control" id="inputQuestion" placeholder="Question" required></textarea>
            </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
<h1>About us!</h1>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Simple question answer app!</h1>
  <p class="lead">This is a simple question answer app made with Rails 4 and PostgreSQL.</p>
</div>

<div class="container">
  <% @questions.each do |q| %>

  <div class="media">
    <img class="d-flex mr-3" src='<%= q.gravatar%>' alt="Generic placeholder image">
    <div class="media-body">
      <h5 class="mt-0 mb-1"> <%= q.email %> asked:</h5>
      <%= time_ago_in_words q.created_at %> ago
      <br/>
      <%= q.body %>
      <div>
        <a href="<%= question_path(q) %>" class="btn btn-success btn-xs">View answers</a>
      </div>
    </div>
  </div>
  <% end %>

  <% if @questions.empty? %>
      <br>
      <div class="alert alert-info">Nothing here yet. Be the first</div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HU</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'home/navigation_bar' %>
  <%= yield %>
  <%= render 'home/new_question_form' %>
  </body>
</html>

app/views/questions/show.html.erb
<div class='container'>
  <div class='card pt-3'>
    <div class='media card'>
      <img class='d-flex mr-3' src='<%= @question.gravatar %>' alt='Generic placeholder image'>
      <div class='media-body'>
        <h5 class='mt-0 mb-1'><%= @question.email %> asked: </h5>
        <%= @question.body %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="pt-3">
      <button class="btn btn-success btn-sm" href="" data-toggle="modal" data-target="#new_answer_modal">Submit new answer</button>
    </div>

    <%= render 'home/new_answer_form' %>

    <% @answers.each do |answer| %>
      <div class="media pt-3">
        <img class="d-flex mr-3" src='<%= answer.gravatar %>' alt="Generic placeholder image">
        <div class="media-body">
          <h5 class="mt-0 mb-1"><%= answer.email %> answered:</h5>
          <%= time_ago_in_words answer.created_at %> ago
          <br/>
          <%= answer.body %>
        </div>
      </div>
    <% end %>

    <% if @answers.empty? %>
        <br>
        <div class="alert alert-info">Nothing here yet. Be the first</div>
    <% end %>
  </div>
</div>